baseurl = "/"
canonifyurls = true
disqusShortname = "http-joelyek-netlify-com"
googleAnalytics = "UA-5243219-9"
languageCode = "en-us"
paginate = 10
theme = "hugo-theme-casper"
title = "Joel Yek"
[params]
author = "Joel Yek"
authorlocation = "Kuala Lumpur, Malaysia"
authorwebsite = "https://joevo2.com/"
cover = "/uploads/2017/10/06/brandon-lam-Dd_7xDCuuUo (1).jpg"
description = "Here is where I do my long form post, anything else tweet me at @joveo2 #react #reactnative #node #developer #anime"
githubname = "joevo2"
googleanalyticsuserid = "UA-5243219-9"
hidehugosupport = false
logo = ""
twittername = "joevo2"
[params.social]
twitter = "joevo2"
